import type { SiteConfig } from "@/types/site";

export const siteConfig: SiteConfig = {
  technicalProjectName: "turkey-travel-market",
  publicBrandName: null,
  defaultLocale: "ru",
  supportedLocales: ["ru"],
  defaultCurrency: "RUB",
  supportedCurrencies: ["RUB"],
  legalCompanyName: "SMART DEVELOPMENT AND TOURISM COMPANY LIMITED / ООО «СМАРТ ДЕВЕЛОПМЕНТ ЭНД ТУРИЗМ»",
  registrationNumber: "0205563015465",
  taxId: null,
  legalAddress: "518/70, Му 9, подрайон Нонг-Пру, район Банг-Ламунг, провинция Чонбури, Таиланд.",
  supportEmail: "supp@turkeyplanners.com",
  supportPhone: null,
  supportHours: null,
  socialLinks: [],
  legalLinks: [],
  paymentMethods: [],
  minimumProductPrice: 50,
  primaryMarket: "Turkey",
  primaryReference: "https://www.floema.com/en",
  nomenclatureReference: "https://online-pattaya.com/",
  description: "Экскурсии, билеты, трансферы и полезные услуги для путешествий по Турции",
};
